---
- hosts: all
  user: dliu
  become: yes
  vars:
    full_name: 'Our Tester'
  tasks:
    - name: deleting linux accout tester
      user:
        name: tester
        state: absent
        remove: yes


